"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cors_1 = require("cors");
var express_1 = require("express");
var app = (0, express_1.default)();
var libraryRoutes_1 = require("./infrastructure/routes/libraryRoutes");
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use(libraryRoutes_1.default);
app.listen(3000, function () { return console.log("Done"); });
